/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as GatewaysSlugRouteImport } from './routes/gateways.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const GatewaysSlugRoute = GatewaysSlugRouteImport.update({
  id: '/gateways/$slug',
  path: '/gateways/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/providers': typeof ProvidersRoute
  '/settings': typeof SettingsRoute
  '/usage': typeof UsageRoute
  '/gateways/$slug': typeof GatewaysSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/providers': typeof ProvidersRoute
  '/settings': typeof SettingsRoute
  '/usage': typeof UsageRoute
  '/gateways/$slug': typeof GatewaysSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/providers': typeof ProvidersRoute
  '/settings': typeof SettingsRoute
  '/usage': typeof UsageRoute
  '/gateways/$slug': typeof GatewaysSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/providers' | '/settings' | '/usage' | '/gateways/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/providers' | '/settings' | '/usage' | '/gateways/$slug'
  id:
    '__root__' | '/' | '/providers' | '/settings' | '/usage' | '/gateways/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProvidersRoute: typeof ProvidersRoute
  SettingsRoute: typeof SettingsRoute
  UsageRoute: typeof UsageRoute
  GatewaysSlugRoute: typeof GatewaysSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gateways/$slug': {
      id: '/gateways/$slug'
      path: '/gateways/$slug'
      fullPath: '/gateways/$slug'
      preLoaderRoute: typeof GatewaysSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProvidersRoute: ProvidersRoute,
  SettingsRoute: SettingsRoute,
  UsageRoute: UsageRoute,
  GatewaysSlugRoute: GatewaysSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
